
version: 2

models:
  - name: stg_event
    description: "Ticketmaster staging transform"
  - name: stg_place
    description: "Staging table for places"
  - name: place
    description: "Normalized deduped places source"
  - name: event
    description: "Normalized deduped events source"
  